// packages/react/components/SellingPoint.tsx
import { styled } from "../stitches.config";
import { StarFilledIcon } from "@modulz/radix-icons";

const Wrapper = styled("div", {});

const Headline = styled("h3", {
  color: "$sage12",
  fontFamily: "Work Sans",
  fontSize: 22,
});

const Description = styled("p", {
  color: "$sage11",
});

const IconWrapper = styled("div", {
  background: "$green7",
  width: 50,
  height: 50,
  borderRadius: 99,
  display: "inline-grid",
  placeContent: "center",
  color: "$sage12",
});

const SellingPoint: React.FunctionComponent<{
  headline: string;
  description: string;
  Icon: JSX.Element;
}> = ({
  headline = "The Headline",
  description = "Here goes the description",
  Icon = StarFilledIcon,
}) => {
  return (
    <Wrapper>
      <IconWrapper>{Icon}</IconWrapper>
      <Headline>{headline}</Headline>
      <Description>{description}</Description>
    </Wrapper>
  );
};

export default SellingPoint;

// packages/svelte/src/components/SellingPoint.svelte
<script lang="ts">
	import Icon from './Icon.svelte';

	export let headline: string = 'The default headline';
	export let description: string = 'The default description';
	export let icon: { name: string; alt: string | undefined } = {
		name: 'starFilledIcon',
		alt: 'the image alt'
	};
</script>

<div>
	<div class="icon-wrapper"><Icon name={icon.name} /></div>
	<h3>{headline}</h3>
	<p>{description}</p>
</div>

<style>
	.icon-wrapper {
		background: var(--green7);
		width: 50px;
		height: 50px;
		border-radius: 99px;
		display: inline-grid;
		place-content: center;
		color: var(--sage12);
	}

	h3 {
		color: var(--sage12);
		font-family: 'Work Sans';
		font-size: 22px;
	}

	p {
		color: var(--sage11);
	}
</style>
