// packages/react/components/StickyBar.tsx
import { styled } from "../stitches.config";
import { useIntersectionObserver } from "../util/hooks";

import SignUp from "./SignUp";

const Wrapper = styled("div", {
  position: "fixed",
  bottom: 0,
  left: 0,
  right: 0,
  padding: 30,

  boxShadow: `0 0 0 1px $green9`,
  background: "rgba(91, 185, 140, 0)",
  backdropFilter: "blur(40px)",

  display: "flex",
  alignItems: "center",
  justifyContent: "space-between",

  flexDirection: "column",
  "@sm": {
    flexDirection: "row",
  },

  variants: {
    shouldBeVisible: {
      true: {
        visibility: "visible",
      },
      false: {
        visibility: "hidden",
      },
    },
  },

  defaultVariants: {
    shouldBeVisible: false,
  },
});

const Text = styled("div", {
  color: "$sage12",
  fontFamily: "Work Sans",
  fontSize: 24,
  flex: 1,

  marginBottom: "$3",
  "@sm": {
    marginBottom: 0,
  },
});

const StickyBar: React.FunctionComponent<{
  elementControllingVisibility: React.MutableRefObject<HTMLDivElement | null>;
}> = ({ elementControllingVisibility }) => {
  const entry = useIntersectionObserver(elementControllingVisibility, {});

  return (
    <Wrapper shouldBeVisible={!entry?.isIntersecting}>
      <Text>Schon entschieden? Dann buch doch einfach mal einen Termin.</Text>
      <SignUp />
    </Wrapper>
  );
};

export default StickyBar;

// packages/svelte/src/components/StickyBar.svelte
<script lang="ts">
import Button from '../components/Button.svelte'
// import IntersectionObserver from '../components/IntersectionObserver.svelte';

// export let elementControllingVisibility;
</script>

<!-- <IntersectionObserver let:intersecting container={elementControllingVisibility}> -->
    <!-- {#if intersecting} -->
<div class="sticky">
    <p>Schon entschieden? Dann buch doch einfach mal einen Termin.</p>
<Button>Termin buchen</Button>
</div>
 <!-- {/if} -->
<!-- </IntersectionObserver> -->


<style>
    .sticky {
        position: fixed;
  bottom: 0px;
  left: 0px;
  right: 0px;
  padding: 30px;

  box-shadow: 0 0 0 1px var(--green9);
  background: rgba(91, 185, 140, 0);
  backdrop-filter: blur(40px);

  display: flex;
  align-items: center;
  justify-content: space-between;

  flex-direction: column;
    }

    @media (min-width: 640px) {
		.sticky {
			flex-direction: row;
		}
	}
    .sticky p {
        color: var(--sage12);
  font-family: "Work Sans";
  font-size: 24px;
  flex: 1;
  margin: 0;

  margin-bottom: var(--space3);

    }

    @media (min-width: 640px) {
		.sticky p  {
			margin-bottom: 0px;
		}
	}
</style>
