// packages/svelte/src/components/SellingPointLarge.svelte
<script lang="ts">
	import Icon from './Icon.svelte';

	export let tag: string = 'The Tag';
	export let headline: string = 'The headline';
	export let description: string[] = ['The description'];
	export let bulletPoints: string[] = ['Bullet point no 1'];
</script>

<div class="wrapper">
	<span class="keyBox">{tag}</span>
	<h3>{headline}</h3>
	<div class="container">
		<div class="box">
			{#each description as paragraph}
				<p>{paragraph}</p>
			{/each}
		</div>
		<div class="box">
			<ul>
				{#each bulletPoints as bulletPoint}
					<li>
						<span class="icon-wrapper"> <Icon name="CheckIcon" /></span>
						<div>{bulletPoint}</div>
					</li>
				{/each}
			</ul>
		</div>
	</div>
</div>

<style>
	.wrapper {
		padding: 40px var(--space5);
	}

	.icon-wrapper {
		border-radius: 99px;
		background: var(--green8);
		color: var(--green12);
		display: inline-grid;
		place-content: center;
		padding: 16px;
		margin-right: 12px;
	}
	ul {
		list-style: none;
		color: var(--sage12);
		margin: 0px;
		padding: 0px;

		margin-top: var(--space2);
	}

	@media (min-width: 640px) {
		ul {
			margin-top: 0px;
			margin-left: var(--space2);
		}
	}

	ul li {
		margin-bottom: 12px;
		display: flex;
		align-items: center;
	}

	ul li:last-of-type {
		margin-bottom: 0px;
	}

	.box {
		flex: 1;
	}
	.container {
		display: flex;
	}

	.keyBox {
		padding: 6px;
		background: var(--green7);
		color: var(--green10);
		border-radius: 4px;
		font-size: 12px;
		font-weight: bold;
	}

	h3 {
		color: var(--sage12);
		font-family: 'Work Sans';
		font-size: 28px;

		margin-top: var(--space2);
		margin-bottom: var(--space4);
	}

	@media (min-width: 640px) {
		h3 {
			padding-right: 50%;
		}
	}
</style>

// packages/react/components/SellingPointLarge.tsx
import { styled } from "../stitches.config";
import { CheckIcon } from "@modulz/radix-icons";

const Box = styled("div", {});

const Headline = styled("h3", {
  color: "$sage12",
  fontFamily: "Work Sans",
  fontSize: 28,

  marginTop: "$2",
  marginBottom: "$4",

  "@sm": {
    paddingRight: "50%",
  },
});

const Description = styled("div", {
  color: "$sage12",
  fontSize: 16,

  "p:first-of-type": {
    marginTop: 0,
  },
});

const KeyBox = styled("span", {
  padding: 6,
  background: "$green7",
  color: "$green10",
  borderRadius: 4,
  fontSize: 12,
  fontWeight: "bold",
});

const IconWrapper = styled("div", {
  borderRadius: 99,
  background: "$green8",
  color: "$green 10",
  display: "inline-grid",
  placeContent: "center",
  padding: 16,
  marginRight: 12,
});

const BulletPointList = styled("ul", {
  listStyle: "none",
  color: "$sage12",
  margin: 0,
  padding: 0,

  marginTop: "$2",

  "@sm": {
    marginTop: 0,
    marginLeft: "$2",
  },

  li: {
    marginBottom: 12,
    display: "flex",
    alignItems: "center",

    "&:last-of-type": {
      marginBottom: 0,
    },
  },
});

const Container = styled("div", {
  display: "flex",

  variants: {
    flexDirection: {
      row: { flexDirection: "row" },
      column: {
        flexDirection: "column",
      },
    },
  },
});

const BulletPoints: React.FunctionComponent<{ bulletPoints: string[] }> = ({
  bulletPoints,
}) => {
  return (
    <BulletPointList>
      {bulletPoints.map((bulletPoint) => (
        <li key={bulletPoint}>
          <IconWrapper>
            <CheckIcon />
          </IconWrapper>
          <div>{bulletPoint}</div>
        </li>
      ))}
    </BulletPointList>
  );
};

const SellingPointLarge: React.FunctionComponent<{
  tag: string;
  headline: string;
  description: string[];
  bulletPoints: string[];
}> = ({ tag, headline, description, bulletPoints }) => {
  return (
    <>
      <KeyBox>{tag}</KeyBox>
      <Headline>{headline}</Headline>
      <Container flexDirection={{ "@initial": "column", "@sm": "row" }}>
        <Box css={{ flex: 1 }}>
          <Description>
            {description.map((paragraph, index) => (
              <p key={index}>{paragraph}</p>
            ))}
          </Description>
        </Box>
        <Box css={{ flex: 1 }}>
          <BulletPoints bulletPoints={bulletPoints} />
        </Box>
      </Container>
    </>
  );
};

export default SellingPointLarge;
